const abi = [
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_factory", type: "address", indexed: false },
      { internal_type: "", name: "_WRON", type: "address", indexed: false },
    ],
    name: "",
    outputs: null,
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
    anonymous: false,
  },
  {
    constant: false,
    inputs: null,
    name: "",
    outputs: null,
    payable: true,
    stateMutability: "payable",
    type: "fallback",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "WRON",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_tokenA", type: "address", indexed: false },
      { internal_type: "", name: "_tokenB", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_amountADesired",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountBDesired",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountAMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountBMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "addLiquidity",
    outputs: [
      { internal_type: "", name: "_amountA", type: "uint256", indexed: false },
      { internal_type: "", name: "_amountB", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_amountTokenDesired",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountTokenMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRONMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "addLiquidityRON",
    outputs: [
      {
        internal_type: "",
        name: "_amountToken",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRON",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: true,
    stateMutability: "payable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "factory",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_reserveIn",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_reserveOut",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "getAmountIn",
    outputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_reserveIn",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_reserveOut",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "getAmountOut",
    outputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
    ],
    name: "getAmountsIn",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
    ],
    name: "getAmountsOut",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      { internal_type: "", name: "_amountA", type: "uint256", indexed: false },
      { internal_type: "", name: "_reserveA", type: "uint256", indexed: false },
      { internal_type: "", name: "_reserveB", type: "uint256", indexed: false },
    ],
    name: "quote",
    outputs: [
      { internal_type: "", name: "_amountB", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_tokenA", type: "address", indexed: false },
      { internal_type: "", name: "_tokenB", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountAMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountBMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "removeLiquidity",
    outputs: [
      { internal_type: "", name: "_amountA", type: "uint256", indexed: false },
      { internal_type: "", name: "_amountB", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountTokenMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRONMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "removeLiquidityRON",
    outputs: [
      {
        internal_type: "",
        name: "_amountToken",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRON",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountTokenMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRONMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "removeLiquidityRONSupportingFeeOnTransferTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amountRON",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountTokenMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRONMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
      { internal_type: "", name: "_approveMax", type: "bool", indexed: false },
      { internal_type: "", name: "_v", type: "uint8", indexed: false },
      { internal_type: "", name: "_r", type: "bytes32", indexed: false },
      { internal_type: "", name: "_s", type: "bytes32", indexed: false },
    ],
    name: "removeLiquidityRONWithPermit",
    outputs: [
      {
        internal_type: "",
        name: "_amountToken",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRON",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountTokenMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountRONMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
      { internal_type: "", name: "_approveMax", type: "bool", indexed: false },
      { internal_type: "", name: "_v", type: "uint8", indexed: false },
      { internal_type: "", name: "_r", type: "bytes32", indexed: false },
      { internal_type: "", name: "_s", type: "bytes32", indexed: false },
    ],
    name: "removeLiquidityRONWithPermitSupportingFeeOnTransferTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amountRON",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_tokenA", type: "address", indexed: false },
      { internal_type: "", name: "_tokenB", type: "address", indexed: false },
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountAMin",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountBMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
      { internal_type: "", name: "_approveMax", type: "bool", indexed: false },
      { internal_type: "", name: "_v", type: "uint8", indexed: false },
      { internal_type: "", name: "_r", type: "bytes32", indexed: false },
      { internal_type: "", name: "_s", type: "bytes32", indexed: false },
    ],
    name: "removeLiquidityWithPermit",
    outputs: [
      { internal_type: "", name: "_amountA", type: "uint256", indexed: false },
      { internal_type: "", name: "_amountB", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactRONForTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: true,
    stateMutability: "payable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactRONForTokensSupportingFeeOnTransferTokens",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactTokensForRON",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactTokensForRONSupportingFeeOnTransferTokens",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactTokensForTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_amountIn", type: "uint256", indexed: false },
      {
        internal_type: "",
        name: "_amountOutMin",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapExactTokensForTokensSupportingFeeOnTransferTokens",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapRONForExactTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: true,
    stateMutability: "payable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountInMax",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapTokensForExactRON",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amountOut",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amountInMax",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_path", type: "address[]", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
    ],
    name: "swapTokensForExactTokens",
    outputs: [
      {
        internal_type: "",
        name: "_amounts",
        type: "uint256[]",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
];

module.exports = abi;
