const abi = [
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_oldAdmin", type: "address", indexed: true },
      { internal_type: "", name: "_newAdmin", type: "address", indexed: true },
    ],
    name: "AdminChanged",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_oldAdmin", type: "address", indexed: true },
    ],
    name: "AdminRemoved",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_owner", type: "address", indexed: true },
      { internal_type: "", name: "_spender", type: "address", indexed: true },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "Approval",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_sender", type: "address", indexed: true },
      { internal_type: "", name: "_amount0", type: "uint256", indexed: false },
      { internal_type: "", name: "_amount1", type: "uint256", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: true },
    ],
    name: "Burn",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_sender", type: "address", indexed: true },
      { internal_type: "", name: "_amount0", type: "uint256", indexed: false },
      { internal_type: "", name: "_amount1", type: "uint256", indexed: false },
    ],
    name: "Mint",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_minter", type: "address", indexed: true },
    ],
    name: "MinterAdded",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_minter", type: "address", indexed: true },
    ],
    name: "MinterRemoved",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_sender", type: "address", indexed: true },
      {
        internal_type: "",
        name: "_amount0In",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amount1In",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amount0Out",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amount1Out",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: true },
    ],
    name: "Swap",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_reserve0", type: "uint112", indexed: false },
      { internal_type: "", name: "_reserve1", type: "uint112", indexed: false },
    ],
    name: "Sync",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_from", type: "address", indexed: true },
      { internal_type: "", name: "_to", type: "address", indexed: true },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "Transfer",
    outputs: null,
    payable: false,
    stateMutability: "",
    type: "event",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internal_type: "", name: "", type: "bytes32", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "MINIMUM_LIQUIDITY",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "PERMIT_TYPEHASH",
    outputs: [{ internal_type: "", name: "", type: "bytes32", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "RON_RELEASE_BLOCK",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "WRON",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_addedMinters",
        type: "address[]",
        indexed: false,
      },
    ],
    name: "addMinters",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "admin",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      { internal_type: "", name: "_owner", type: "address", indexed: false },
      { internal_type: "", name: "_spender", type: "address", indexed: false },
    ],
    name: "allowance",
    outputs: [
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_spender", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "approve",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    name: "balanceOf",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "burn",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_to", type: "address", indexed: false },
    ],
    name: "burn",
    outputs: [
      { internal_type: "", name: "_amount0", type: "uint256", indexed: false },
      { internal_type: "", name: "_amount1", type: "uint256", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_from", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "burnFrom",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_newAdmin", type: "address", indexed: false },
    ],
    name: "changeAdmin",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "decimals",
    outputs: [{ internal_type: "", name: "", type: "uint8", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "factory",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "getReserves",
    outputs: [
      { internal_type: "", name: "", type: "uint112", indexed: false },
      { internal_type: "", name: "", type: "uint112", indexed: false },
      { internal_type: "", name: "", type: "uint32", indexed: false },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_token0", type: "address", indexed: false },
      { internal_type: "", name: "_token1", type: "address", indexed: false },
      { internal_type: "", name: "_admin", type: "address", indexed: false },
      { internal_type: "", name: "_name", type: "string", indexed: false },
      { internal_type: "", name: "_symbol", type: "string", indexed: false },
    ],
    name: "initialize",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [
      { internal_type: "", name: "_addr", type: "address", indexed: false },
    ],
    name: "isMinter",
    outputs: [{ internal_type: "", name: "", type: "bool", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "mint",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_to", type: "address", indexed: false },
    ],
    name: "mint",
    outputs: [
      {
        internal_type: "",
        name: "_liquidity",
        type: "uint256",
        indexed: false,
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    name: "minter",
    outputs: [{ internal_type: "", name: "", type: "bool", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    name: "minters",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [{ internal_type: "", name: "", type: "string", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    name: "nonces",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_owner", type: "address", indexed: false },
      { internal_type: "", name: "_spender", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
      { internal_type: "", name: "_deadline", type: "uint256", indexed: false },
      { internal_type: "", name: "_v", type: "uint8", indexed: false },
      { internal_type: "", name: "_r", type: "bytes32", indexed: false },
      { internal_type: "", name: "_s", type: "bytes32", indexed: false },
    ],
    name: "permit",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "price0CumulativeLast",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "price1CumulativeLast",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [],
    name: "removeAdmin",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_removedMinters",
        type: "address[]",
        indexed: false,
      },
    ],
    name: "removeMinters",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_to", type: "address", indexed: false },
    ],
    name: "skim",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      {
        internal_type: "",
        name: "_amount0Out",
        type: "uint256",
        indexed: false,
      },
      {
        internal_type: "",
        name: "_amount1Out",
        type: "uint256",
        indexed: false,
      },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "", type: "bytes", indexed: false },
    ],
    name: "swap",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [{ internal_type: "", name: "", type: "string", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [],
    name: "sync",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "token0",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "token1",
    outputs: [{ internal_type: "", name: "", type: "address", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: true,
    inputs: [],
    name: "totalSupply",
    outputs: [{ internal_type: "", name: "", type: "uint256", indexed: false }],
    payable: false,
    stateMutability: "view",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "transfer",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
  {
    constant: false,
    inputs: [
      { internal_type: "", name: "_from", type: "address", indexed: false },
      { internal_type: "", name: "_to", type: "address", indexed: false },
      { internal_type: "", name: "_value", type: "uint256", indexed: false },
    ],
    name: "transferFrom",
    outputs: [
      { internal_type: "", name: "_success", type: "bool", indexed: false },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
    anonymous: false,
  },
];

module.exports = abi;
